# Based loosely on inspection of neovim's internal lua runtime files.

column_width = 120
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferSingle"
call_parentheses = "Always"
collapse_simple_statement = "Never"

[sort_requires]
enabled = false
